### ISSUE TITLE
This  needs to be if its NOT null xD

### ISSUE THREAD

**Issue by robmerki** [CognitiveVR/cvr-sdk-unity#3]
https://github.com/CognitiveVR/cvr-sdk-unity/blob/38c7649a7758c8159f1f38d53b6a3817995cf4df/CognitiveVRUnity/UnityPlugin/CoreSubsystem.cs#L31

**Comment by calderarchinuk** [comment]
fixed in this commit [38c7649](https://github.com/CognitiveVR/cvr-sdk-unity/commit/2317f86ec607dc05607a103ca5dd4646fbc77919)
